name = "KolmogorovZurbenkoFilters"
uuid = "1c1c24aa-c5e8-4ac4-949f-20023cef821f"
authors = ["Leif Denby <leif@denby.eu> and contributors"]
version = "0.1.0"

<<<<<<< Updated upstream
=======
[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

>>>>>>> Stashed changes
[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
